policy_name: ViTAL
kind: act
batch_size: 64
num_epochs: 4000
chunk_size: 20
kl_weight: 10.0
z_dimension: 32
dropout: 0.025
backbone: clip_backbone
lr: 0.00001
lr_backbone: 0.00001
weight_decay: 0.0001
hidden_dim: 512
dim_feedforward: 3200
enc_layers: 4
dec_layers: 7
nheads: 8
temporal_agg: false
gelsight_backbone_path: checkpoints/VITAL_encoder/gelsight_encoder.pth
vision_backbone_path: checkpoints/VITAL_encoder/vision_encoder.pth
